### ISSUE TITLE
Potential blocking of threadpool

### ISSUE THREAD

**Issue by davisjam** [briandk/transcriptase#26]
In `main.js` you call `fs.readFile` rather than opening a read file stream and buffering incoming data until it finishes.

If the input files are really big, this can make your app unresponsive (consumes one of the threadpool threads). If the user can request that you open `/dev/null`, it'll crash your application.

This might be needlessly paranoid, but hey, why not?

**Comment by briandk** [comment]
Isn't node reading the file asynchronously?

https://nodejs.org/api/fs.html#fs_fs_readfile_file_options_callback

**Comment by davisjam** [comment]
Yep, wrote the wrong thing in the title. Fixed now.

Node reads the file "asynchronously", but `fs.readFile` gets a dedicated threadpool thread until the entire read has completed. In other words, Node doesn't use true AIO, it just moves the synchronous IO to the threadpool. If the read is expensive (e.g. big file or from a "bottomless I/O source" like /dev/null), the threadpool thread goes out to lunch.

The stream-oriented APIs serve up the file in fixed-size chunks, which you can buffer until the stream finishes. The threadpool thread can be used for other things in the meantime, e.g. allowing "short and fast" operations to finish up quickly.

Node defaults to 4 threadpool threads so blocking a thread can have a noticeable impact on the application, if you're a heavy user of the threadpool.

This is probably needlessly paranoid for transcriptase, but IMHO it's good practice.

**Comment by briandk** [comment]
@davisjam So, generally in open source development, bug reports < proposed solutions < pull request.

What would be your proposed solution?

**Comment by davisjam** [comment]
@briandk I figured I would open the report and see what you thought before proposing a PR.

If you're open to using a read stream, I'll cook one up. Let me know.

**Comment by briandk** [comment]
@davisjam sure! Let's see what you cook up

**Comment by briandk** [comment]
Right now, not I think this is an edge-case
